### ISSUE TITLE
Cannot Import module 'querybase'. 

### ISSUE THREAD

**Issue by niteshtak** [davideast/Querybase#34]
Error: Cannot find module 'querybase'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

**Comment by niteshtak** [comment]
Change a line '/dist/main...' to 'dist/main....' in package.json in query base module.
